# Generated by Django 4.0 on 2021-12-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200)),
                ('last_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
