# Generated by Django 4.0 on 2021-12-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_teammember_delete_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone_number',
            field=models.IntegerField(default='0'),
        ),
    ]
