# Generated by Django 4.0 on 2021-12-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_teammember_email_teammember_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.IntegerField(default=0, verbose_name=[(0, 'Regular'), (1, 'Admin')]),
        ),
    ]
