# Generated by Django 4.0 on 2021-12-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='profile_picture',
            field=models.CharField(default='employees/templates/icons/profile_icon.jpg', max_length=200),
        ),
    ]
