# Generated by Django 4.0 on 2021-12-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_teammember_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='profile_picture',
            field=models.CharField(default='profile_icon.jpg', max_length=200),
        ),
    ]
