# Generated by Django 4.0 on 2022-01-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_teammember_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.AddField(
            model_name='teammember',
            name='member_index',
            field=models.IntegerField(default=0),
        ),
    ]
