# Generated by Django 4.0 on 2022-01-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_teammember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='id',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_index',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
