# Generated by Django 4.0 on 2022-01-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_teammember_id_alter_teammember_member_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='member_index',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
