# Generated by Django 4.0 on 2022-01-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_teammember_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone_number',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
